Repository fusionjs/fusion-plugin-introspect, pull requests merged in 2018-12, with the labels that each got.

#14 Fix lint
  src/collectMetadata.js
  src/server.js
Labels: bugfix

#18 Add `Try it out` section; Update package description
  README.md
  package.json
Labels: bugfix

#17 Add CLI docs
  README.md
Labels: docs

#19 Fix typo
  README.md
Labels: docs

#23 Release v0.2.3
  package.json
Labels: release

#24 Fix lock file
  yarn.lock
Labels: bugfix

#25 Release v0.2.4
  package.json
Labels: release

#26 Synchronize server and browser type
  src/browser.js
Labels: bugfix

#27 Release v0.2.5
  package.json
Labels: release

#28 Ensure no error is thrown on browser due to plugin-ness of export
  src/browser.js
Labels: bugfix

#29 Release v0.2.6
  package.json
Labels: release

#30 Ensure .fusion folder exists
  src/fs-store.js
Labels: bugfix

#31 Release v0.2.7
  package.json
Labels: release

#32 Use absolute paths in browser to avoid bundling a bunch of node polyfills
  src/collectDependencyData.js
Labels: bugfix

#33 Release v0.2.8
  package.json
Labels: release

#36 Fix cli examples
  README.md
Labels: docs

#37 Force a non-zero content-length to avoid weird edge cases
  src/collectDependencyData.js
  src/server.js
Labels: bugfix

#38 Release v0.2.10
  package.json
Labels: release
