Repository fusionjs/fusion-plugin-introspect, pull requests merged in 2018-11, with the labels that each got.

#7 Implement CLI
  .eslintignore
  .eslintrc.js
  flow-typed/npm/jest_v23.x.x.js
  package.json
  src/__tests__/browser.browser.js
  src/__tests__/cli/__snapshots__/middleware.node.js.snap
  src/__tests__/cli/__snapshots__/sortDependencies.node.js.snap
  src/__tests__/cli/__snapshots__/why.node.js.snap
  src/__tests__/cli/getMaxWordWidth.node.js
  src/__tests__/cli/listDependencies.node.js
  src/__tests__/cli/listSourceLines.node.js
  src/__tests__/cli/middleware.node.js
  src/__tests__/cli/mockFs.js
  src/__tests__/cli/parseRuntimeMetadata.node.js
  src/__tests__/cli/sortDependencies.node.js
  src/__tests__/cli/tokens.node.js
  src/__tests__/cli/where.node.js
  src/__tests__/cli/why.node.js
  src/__tests__/collectDependencyData.node.js
  src/__tests__/collectMetadata.node.js
  src/__tests__/exec.node.js
  src/__tests__/fs-store.node.js
  src/__tests__/index.browser.js
  src/__tests__/index.node.js
  src/__tests__/server.node.js
  src/cli/getMaxWordWidth.js
  src/cli/index.js
  src/cli/listDependencies.js
  src/cli/listSourceLines.js
  src/cli/logs.js
  src/cli/middleware.js
  src/cli/parseRuntimeMetadata.js
  src/cli/sortDependencies.js
  src/cli/tokens.js
  src/cli/types.js
  src/cli/where.js
  src/cli/why.js
  src/collectDependencyData.js
  src/collectMetadata.js
  yarn.lock
Labels: feature

#8 Release v0.2.0
  package.json
Labels: release

#9 Fix types
  package.json
  src/collectDependencyData.js
  yarn.lock
Labels: bugfix

#10 Release v0.2.1-0
  package.json
Labels: release

#11 Release v0.2.1
  package.json
Labels: release

#13 Upgrade dependencies
  package.json
  yarn.lock
Labels: greenkeeping
